version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "weplate-task:$TASK_REVISION"
        LoadBalancerInfo:
          ContainerName: nginx
          ContainerPort: 80
