version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinitionArn: "$TASK_DEFINITION_ARN"
        LoadBalancerInfo:
          ContainerName: nginx
          ContainerPort: 80
