version: '3'
services:
  client-weplate:
    container_name: client-weplate
    build:
      context: .
      dockerfile: apps/client-weplate/Dockerfile
    ports:
      - "1111:1111"
  
  server-api:
    container_name: server-api
    build:
      context: .
      dockerfile: apps/server-api/Dockerfile
    ports:
      - "7777:7777"

  server-auth:
    container_name: server-auth
    build:
      context: .
      dockerfile: apps/server-auth/Dockerfile
    ports:
      - "5555:5555"

  nginx:
    container_name: nginx
    build: apps/nginx
    ports:
      - "80:80"
    depends_on:
      - client-weplate
      - server-api
      - server-auth
