version: '3.8'
services:
  client-weplate:
    container_name: client-weplate
    build:
      context: .
      dockerfile: apps/client-weplate/Dockerfile
    image: $ECR_REGISTRY/weplate/client-weplate:$VERSION
    ports:
      - "1111:1111"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1024M

  server-api:
    container_name: server-api
    build:
      context: .
      dockerfile: apps/server-api/Dockerfile
    image: $ECR_REGISTRY/weplate/server-api:$VERSION
    ports:
      - "7777:7777"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 512M

  server-auth:
    container_name: server-auth
    build:
      context: .
      dockerfile: apps/server-auth/Dockerfile
    image: $ECR_REGISTRY/weplate/server-auth:$VERSION
    ports:
      - "5555:5555"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 512M

  nginx:
    container_name: nginx
    build: apps/nginx
    image: $ECR_REGISTRY/weplate/nginx:$VERSION
    ports:
      - "80:80"
    depends_on:
      - client-weplate
      - server-api
      - server-auth
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 256M

  nginx-health-check:
    container_name: nginx-health-check
    build: apps/nginx
    image: $ECR_REGISTRY/weplate/nginx:$VERSION
    ports:
      - "8080:80"
    depends_on:
      - client-weplate
      - server-api
      - server-auth
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 256M
