name: Release
run-name: ${{ github.actor }} start release. 🚀
on:
  pull_request:
    types:
      - closed
    branches:
      - main
jobs:
  Merge-Master-Branch-In-Develop-Branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge master -> develop
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: main
          target_branch: develop
          github_token: ${{ secrets.GITHUB_TOKEN }}
