name: Release PR Check
run-name: ${{ github.actor }} attempts to merge the release branch. 🚀
on:
  pull_request:
    branches:
      - main
jobs:
  Test-Develop-Merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Fetch all branches
        run: git fetch --all

      - name: Set up Git user information
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Checkout develop branch
        run: git checkout develop

      - name: Cat Files
        run: cat README.md

      - name: Attempt to merge PR branch into develop
        run: |
          git merge --no-commit --no-ff --allow-unrelated-histories ${{ github.event.pull_request.head.ref }} || (
            echo "Merge conflict detected with develop branch!" && exit 1
          )

      - name: Merge successful
        if: success()
        run: echo "The branch can be merged into develop successfully!"
