name: Release PR Check
run-name: ${{ github.actor }} attempts to merge the release branch. 🚀
on:
  pull_request:
    branches:
      - main
jobs:
  Test-Develop-Merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Fetch develop branches
        run: |
          git fetch origin develop

      - name: Test mergeability of release to develop
        id: merge-test
        run: |
          git checkout develop
          git merge --no-commit --no-ff --allow-unrelated-histories ${{ github.event.pull_request.head.ref }} || echo "::set-output name=mergeable::false"
          echo "::set-output name=mergeable::true"

      - name: Output mergeability result
        run: |
          if [ "${{ steps.merge-test.outputs.mergeable }}" == "false" ]; then
            echo "Merge conflict detected between release and develop."
            exit 1
          else
            echo "Release branch can be merged into develop without conflicts."
          fi
